import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import CheckConstraint, Date, DateTime, Index, Numeric, String, func
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base


class Expense(Base):
    __tablename__ = "expenses"

    id: Mapped[str] = mapped_column(
        String, primary_key=True, default=lambda: str(uuid.uuid4())
    )
    user_id: Mapped[str] = mapped_column(String, nullable=False)
    category_id: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(String, nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(12, 2), nullable=False)
    currency: Mapped[str] = mapped_column(String(3), nullable=False, default="PHP")
    spent_on: Mapped[date] = mapped_column(Date, nullable=False)

    # Reserved for M4 (installments)
    installment_group_id: Mapped[str | None] = mapped_column(String, nullable=True)
    installment_index: Mapped[int | None] = mapped_column(nullable=True)
    installment_total: Mapped[int | None] = mapped_column(nullable=True)
    original_description: Mapped[str | None] = mapped_column(String, nullable=True)

    # Set when this row was generated by the recurring-expense worker job (BUD-38)
    recurring_expense_id: Mapped[str | None] = mapped_column(String, nullable=True)

    # Reserved for M6 (households)
    household_id: Mapped[str | None] = mapped_column(String, nullable=True)

    # Reserved for M7 (multi-currency conversion)
    base_amount: Mapped[Decimal | None] = mapped_column(Numeric(12, 2), nullable=True)
    exchange_rate: Mapped[Decimal | None] = mapped_column(Numeric(18, 6), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    __table_args__ = (
        CheckConstraint("amount > 0", name="ck_expenses_amount_positive"),
        CheckConstraint("description <> ''", name="ck_expenses_description_nonempty"),
        CheckConstraint(
            "(installment_group_id IS NULL AND installment_index IS NULL "
            "AND installment_total IS NULL AND original_description IS NULL) "
            "OR (installment_group_id IS NOT NULL AND installment_index IS NOT NULL "
            "AND installment_total IS NOT NULL AND original_description IS NOT NULL "
            "AND installment_total >= 2 AND installment_index >= 1 "
            "AND installment_index <= installment_total)",
            name="ck_expenses_installment_metadata",
        ),
        Index("ix_expenses_user_spent_on", "user_id", "spent_on"),
        Index("ix_expenses_installment_group_id", "installment_group_id"),
        Index(
            "ux_expenses_recurring_expense_id_spent_on",
            "recurring_expense_id",
            "spent_on",
            unique=True,
        ),
    )
